### ISSUE TITLE
Sample uses Node.js 14.6.0 - Node 14 is EOL 04-30-2023

### ISSUE THREAD

**Issue by lmbr-pip** [aws-samples/aws-gamelift-and-serverless-backend-sample#10]
Sample asks to `Install Node.js 14.6.0` in README.md.

Please note NodeJS is EOL 04-30 2023, see https://github.com/nodejs/release#release-schedule

## Expected Behaviour
* Uses stable LTS version of NodeJS such as 18.x

**Comment by juhoaws** [comment]
Fixed
