### ISSUE TITLE
README states eu-west-2 is secondary region but code uses eu-west-1

### ISSUE THREAD

**Issue by lmbr-pip** [aws-samples/aws-gamelift-and-serverless-backend-sample#11]
README states: 

> The default AWS Regions for the solution are us-east-1 for backend and GameLift home region and **eu-west-2** for GameLift secondary region 

Code uses:

https://github.com/aws-samples/aws-gamelift-and-serverless-backend-sample/blob/54f2b29068a424bea61a84dbfd1ca9a545fd029f/CppServerAndClient/Client/Client.h#L18

**Comment by juhoaws** [comment]
Fixed
